### ISSUE TITLE
Update Tests of GET API

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#82]
GET API Tests are not updated for the pagination feature, 
All the tests in controllers, managers, services shall be updated as per the latest version of GET API.

**Comment by Sukriti-sood** [comment]
I wan to work on this

**Comment by jnv27** [comment]
Hey @Manvityagi I would like to work on this issue and I've sent PR for my previous issue as well you can check and merge it.

**Comment by Kashish0423** [comment]
Hello @Manvityagi mam , i just got my previous issue merged , can I take this issue ?

**Comment by Manvityagi** [comment]
Sorry for the delay guys, 
As per FCFS, @Sukriti-sood assigned to you

**Comment by Manvityagi** [comment]
@Sukriti-sood Please update the tests asap, as the build is currently failing and that is probably because of the same issue.

**Comment by Sukriti-sood** [comment]
> @Sukriti-sood Please update the tests asap, as the build is currently failing and that is probably because of the same issue.

Ook

**Comment by Sukriti-sood** [comment]
@Manvityagi  Is there any limit to page query value........?

**Comment by Sukriti-sood** [comment]
@Manvityagi  I am unable to resolve following error:-
![Screenshot from 2021-05-02 17-54-23](https://user-images.githubusercontent.com/55010599/116813086-b61cea80-ab6f-11eb-93a8-d6675618d4bb.png)

If image not uploaded due to any issue:-
` OpportunityManager
       getOpportunities
         should retrieve Opportunities with specific opportunityType:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/sukriti/Desktop/Opportunity-Calendar-Backend/tests/managers/opportunity-test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)`

**Comment by Manvityagi** [comment]
> @Manvityagi I am unable to resolve following error:-
> ![Screenshot from 2021-05-02 17-54-23](https://user-images.githubusercontent.com/55010599/116813086-b61cea80-ab6f-11eb-93a8-d6675618d4bb.png)
> 
> If image not uploaded due to any issue:-
> ` OpportunityManager getOpportunities should retrieve Opportunities with specific opportunityType: Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/sukriti/Desktop/Opportunity-Calendar-Backend/tests/managers/opportunity-test.js) at listOnTimeout (internal/timers.js:554:17) at processTimers (internal/timers.js:497:7)`


Take the latest pull, this error is resolved now.

**Comment by ria-19** [comment]
Is this still open? I would like to contribute to this project.

**Comment by ghost** [comment]
can i get assigned to this task please? i am a GSSOC"23 participant

**Comment by jnv27** [comment]
@***@***.*** ***@***.***>  can you assign this issue
to him?
